import Foundation

public struct IntegrationPrivacyPolicy: Codable, Equatable, Sendable {
    public static let currentVersion = 1

    public var version: Int
    public var assistantExcerptsEnabled: Bool

    public init(assistantExcerptsEnabled: Bool = false) {
        version = Self.currentVersion
        self.assistantExcerptsEnabled = assistantExcerptsEnabled
    }

    public static func load(from url: URL) -> Self {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return Self() }
        defer { try? handle.close() }
        guard
            let data = try? handle.read(upToCount: 4_097),
            data.count <= 4_096,
            let policy = try? JSONDecoder().decode(Self.self, from: data),
            policy.version == currentVersion
        else {
            return Self()
        }
        return policy
    }
}

public enum NotchBotIntegrationFiles {
    public static let generatedMarker = "Generated by NotchBot integration v0.2.4-r11"
    public static let previousGeneratedMarkers = [
        "Generated by NotchBot integration v0.2.3-r11",
        "Generated by NotchBot integration v0.2.3",
        "Generated by NotchBot integration v0.2.2",
        "Generated by NotchBot integration v0.2.1",
        "Generated by NotchBot integration v0.2",
    ]
    public static let helperOwnershipMarker = "NotchBot managed helper v0.2.4-r11\n"
    public static let previousHelperOwnershipMarkers = [
        "NotchBot managed helper v0.2.3-r11\n",
        "NotchBot managed helper v0.2.3\n",
        "NotchBot managed helper v0.2.2\n",
        "NotchBot managed helper v0.2.1\n",
        "NotchBot managed helper v0.2\n",
    ]

    public static func privacyPolicyURL(applicationSupportDirectory: URL) -> URL {
        applicationSupportDirectory.appendingPathComponent("integration-privacy.json")
    }

    public static func installStatusURL(applicationSupportDirectory: URL) -> URL {
        applicationSupportDirectory.appendingPathComponent("integration-installation.json")
    }

    public static func helperOwnershipURL(helperURL: URL) -> URL {
        helperURL.appendingPathExtension("notchbot-owner")
    }

    public static func backupDirectoryURL(applicationSupportDirectory: URL) -> URL {
        applicationSupportDirectory.appendingPathComponent("integration-backups", isDirectory: true)
    }
}

public struct IntegrationInstallStatus: Codable, Equatable, Sendable {
    public static let currentVersion = 11

    public let version: Int
    public let installedAt: Date

    public init(installedAt: Date = Date()) {
        version = Self.currentVersion
        self.installedAt = installedAt
    }
}
