import Foundation

public enum NotchBotIntegrationFiles {
    public static let generatedMarker = "Generated by NotchBot integration v0.2.5-r12"
    public static let previousGeneratedMarkers = [
        "Generated by NotchBot integration v0.2.4-r12",
        "Generated by NotchBot integration v0.2.4-r11",
        "Generated by NotchBot integration v0.2.3-r11",
        "Generated by NotchBot integration v0.2.3",
        "Generated by NotchBot integration v0.2.2",
        "Generated by NotchBot integration v0.2.1",
        "Generated by NotchBot integration v0.2",
    ]
    public static let helperOwnershipMarker = "NotchBot managed helper v0.2.5-r12\n"
    public static let previousHelperOwnershipMarkers = [
        "NotchBot managed helper v0.2.4-r12\n",
        "NotchBot managed helper v0.2.4-r11\n",
        "NotchBot managed helper v0.2.3-r11\n",
        "NotchBot managed helper v0.2.3\n",
        "NotchBot managed helper v0.2.2\n",
        "NotchBot managed helper v0.2.1\n",
        "NotchBot managed helper v0.2\n",
    ]

    public static func installStatusURL(applicationSupportDirectory: URL) -> URL {
        applicationSupportDirectory.appendingPathComponent("integration-installation.json")
    }

    public static func helperOwnershipURL(helperURL: URL) -> URL {
        helperURL.appendingPathExtension("notchbot-owner")
    }

    public static func backupDirectoryURL(applicationSupportDirectory: URL) -> URL {
        applicationSupportDirectory.appendingPathComponent("integration-backups", isDirectory: true)
    }

}

public struct IntegrationInstallStatus: Codable, Equatable, Sendable {
    public static let currentVersion = 12

    public let version: Int
    public let installedAt: Date

    public init(installedAt: Date = Date()) {
        version = Self.currentVersion
        self.installedAt = installedAt
    }
}
