import Foundation

public enum NotchBotIntegrationFiles {
    public static let generatedMarker = "Generated by NotchBot integration v0.9.0-r20"
    public static let previousGeneratedMarkers = [
        "Generated by NotchBot integration v0.6.0-r19",
        "Generated by NotchBot integration v0.5.0-r18",
        "Generated by NotchBot integration v0.4.0-r17",
        "Generated by NotchBot integration v0.3.2-r17",
        "Generated by NotchBot integration v0.3.2-r16",
        "Generated by NotchBot integration v0.3.2-r15",
        "Generated by NotchBot integration v0.3.1-r14",
        "Generated by NotchBot integration v0.3.0-r13",
        "Generated by NotchBot integration v0.2.5-r12",
        "Generated by NotchBot integration v0.2.4-r12",
        "Generated by NotchBot integration v0.2.4-r11",
        "Generated by NotchBot integration v0.2.3-r11",
        "Generated by NotchBot integration v0.2.3",
        "Generated by NotchBot integration v0.2.2",
        "Generated by NotchBot integration v0.2.1",
        "Generated by NotchBot integration v0.2",
    ]
    public static let helperOwnershipMarker = "NotchBot managed helper v0.9.0-r20\n"
    public static let previousHelperOwnershipMarkers = [
        "NotchBot managed helper v0.6.0-r19\n",
        "NotchBot managed helper v0.5.0-r18\n",
        "NotchBot managed helper v0.4.0-r17\n",
        "NotchBot managed helper v0.3.2-r17\n",
        "NotchBot managed helper v0.3.2-r16\n",
        "NotchBot managed helper v0.3.2-r15\n",
        "NotchBot managed helper v0.3.1-r14\n",
        "NotchBot managed helper v0.3.0-r13\n",
        "NotchBot managed helper v0.2.5-r12\n",
        "NotchBot managed helper v0.2.4-r12\n",
        "NotchBot managed helper v0.2.4-r11\n",
        "NotchBot managed helper v0.2.3-r11\n",
        "NotchBot managed helper v0.2.3\n",
        "NotchBot managed helper v0.2.2\n",
        "NotchBot managed helper v0.2.1\n",
        "NotchBot managed helper v0.2\n",
    ]

    public static func installStatusURL(applicationSupportDirectory: URL) -> URL {
        applicationSupportDirectory.appendingPathComponent("integration-installation.json")
    }

    public static func helperOwnershipURL(helperURL: URL) -> URL {
        helperURL.appendingPathExtension("notchbot-owner")
    }

    public static func backupDirectoryURL(applicationSupportDirectory: URL) -> URL {
        applicationSupportDirectory.appendingPathComponent("integration-backups", isDirectory: true)
    }

}

public struct IntegrationInstallStatus: Codable, Equatable, Sendable {
    public static let currentVersion = 20

    public let version: Int
    public let installedAt: Date

    public init(installedAt: Date = Date()) {
        version = Self.currentVersion
        self.installedAt = installedAt
    }
}
