import Foundation

public enum OpenCodePlugin {
    public static func generate(hookPath: String, assistantExcerptsEnabled: Bool) -> String {
        let pathLiteral = jsonString(hookPath)
        let excerptStorage = assistantExcerptsEnabled ? enabledExcerptStorage : ""
        let eventCapture = assistantExcerptsEnabled ? enabledEventCapture : ""
        let attentionSummary = assistantExcerptsEnabled
            ? "const summary = takeResponse(sessionID)"
            : "const summary = null"
        let errorCleanup = assistantExcerptsEnabled ? "\n            latestResponses.delete(sessionID)" : ""
        let deletionCleanup = assistantExcerptsEnabled ? "\n            latestResponses.delete(sessionID)" : ""

        return """
        // \(NotchBotIntegrationFiles.generatedMarker). Do not edit.
        const hookPath = \(pathLiteral)
        \(excerptStorage)
        function bounded(value, maximum) {
          if (typeof value !== "string" || value.length === 0) return null
          return value.length > maximum ? value.slice(0, maximum) : value
        }

        function send(kind, sessionID, reason, directory, expiresAfter, summary) {
          const args = [hookPath, "--source", "opencode", "--kind", kind]
          if (reason) args.push("--reason", reason)
          if (expiresAfter) args.push("--expires-after", String(expiresAfter))
          const payload = {
            session_id: bounded(sessionID, 128),
            cwd: bounded(directory, 1024),
          }
          if (summary) payload.last_assistant_message = summary
          try {
            const child = Bun.spawn(args, { stdin: "pipe", stdout: "ignore", stderr: "ignore" })
            child.stdin.write(JSON.stringify(payload))
            child.stdin.end()
            child.unref()
          } catch (_) {
            // The optional NotchBot UI may not be available.
          }
        }

        export const NotchBot = async ({ directory }) => ({
          event: async ({ event }) => {
            const properties = event.properties ?? {}
            const sessionID = properties.sessionID ?? properties.info?.id
        \(eventCapture)
            if (!sessionID) return

            switch (event.type) {
              case "session.status":
                if (properties.status?.type === "busy" || properties.status?.type === "retry") {
                  send("working", sessionID, null, directory, null, null)
                } else if (properties.status?.type === "idle") {
                  \(attentionSummary)
                  send("attention", sessionID, "OpenCode finished working", directory, 2.5, summary)
                }
                break
              case "session.idle": {
                \(attentionSummary)
                send("attention", sessionID, "OpenCode finished working", directory, 2.5, summary)
                break
              }
              case "permission.asked":
              case "permission.v2.asked":
                send("attention", sessionID, "OpenCode needs permission", directory, null, null)
                break
              case "question.asked":
              case "question.v2.asked":
                send("attention", sessionID, "OpenCode has a question", directory, null, null)
                break
              case "permission.replied":
              case "permission.v2.replied":
              case "question.replied":
              case "question.v2.replied":
              case "question.rejected":
              case "question.v2.rejected":
                send("working", sessionID, null, directory, null, null)
                break
              case "session.error":
                send("attention", sessionID, "OpenCode encountered an error", directory, null, null)\(errorCleanup)
                break
              case "session.deleted":
                send("cleared", sessionID, null, directory, null, null)\(deletionCleanup)
                break
            }
          },
          "tool.execute.before": async (input) => {
            send("working", input.sessionID, null, directory, null, null)
          },
        })
        """
    }

    public static func isOwned(_ contents: String) -> Bool {
        contents.hasPrefix("// \(NotchBotIntegrationFiles.generatedMarker).")
    }

    public static func isLegacyV01(_ contents: String) -> Bool {
        contents.hasPrefix("// Generated by NotchBot. Remove this file")
            && contents.contains("const latestResponses = new Map()")
            && contents.contains("Bun.spawn(args")
            && contents.contains("--source\", \"opencode")
    }

    private static func jsonString(_ value: String) -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.withoutEscapingSlashes]
        let data = try! encoder.encode(value)
        return String(decoding: data, as: UTF8.self)
    }

    private static let enabledExcerptStorage = """

        const messageSessions = new Map()
        const latestResponses = new Map()

        function setBounded(map, key, value) {
          if (!map.has(key) && map.size >= 256) map.delete(map.keys().next().value)
          map.set(key, value)
        }

        function excerpt(value) {
          if (typeof value !== "string") return null
          const normalized = value.replace(/\\s+/g, " ").trim()
          return normalized.length > 240 ? normalized.slice(0, 237).trimEnd() + "..." : normalized
        }

        function takeResponse(sessionID) {
          const response = latestResponses.get(sessionID) ?? null
          latestResponses.delete(sessionID)
          return response
        }
    """

    private static let enabledEventCapture = """

            if (event.type === "message.updated" && properties.info?.role === "assistant") {
              setBounded(messageSessions, properties.info.id, properties.info.sessionID)
            }
            if (event.type === "message.part.updated" && properties.part?.type === "text") {
              const partSessionID = messageSessions.get(properties.part.messageID)
              const response = excerpt(properties.part.text)
              if (partSessionID && response) setBounded(latestResponses, partSessionID, response)
            }
    """
}
