import Foundation

public enum OpenCodePlugin {
    public static func generate(hookPath: String, includeCostTracking: Bool = false) -> String {
        let substitutions = [
            ("{{MARKER}}", NotchBotIntegrationFiles.generatedMarker),
            ("{{USAGE_STATE}}", includeCostTracking ? OpenCodePluginSource.usageState : ""),
            ("{{USAGE_HELPERS}}", includeCostTracking ? OpenCodePluginSource.usageHelpers : ""),
            ("{{USAGE_PAYLOAD}}", includeCostTracking ? OpenCodePluginSource.usagePayload : ""),
            ("{{USAGE_EVENT}}", includeCostTracking ? OpenCodePluginSource.usageEvent : ""),
            ("{{USAGE_PARAMS}}", includeCostTracking ? OpenCodePluginSource.usageParams : ""),
            ("{{USAGE_CLEANUP}}", includeCostTracking ? OpenCodePluginSource.usageCleanup : ""),
            ("{{HOOK_PATH}}", jsonString(hookPath)),
        ]
        return substitutions.reduce(OpenCodePluginSource.template) {
            $0.replacingOccurrences(of: $1.0, with: $1.1)
        }
    }

    public static func isOwned(_ contents: String) -> Bool {
        hasGeneratedHeader(NotchBotIntegrationFiles.generatedMarker, in: contents)
    }

    public static func isPreviousVersion(_ contents: String) -> Bool {
        NotchBotIntegrationFiles.previousGeneratedMarkers.contains { hasGeneratedHeader($0, in: contents) }
            && contents.contains("function send(kind, sessionID")
            && contents.contains("Bun.spawn(args")
            && contents.contains("case \"session.status\"")
            && contents.contains("\"tool.execute.before\"")
    }

    public static func isLegacyV01(_ contents: String) -> Bool {
        contents.hasPrefix("// Generated by NotchBot. Remove this file")
            && contents.contains("export const NotchBot")
            && contents.contains("Bun.spawn(args")
            && contents.contains("process.unref()")
            && contents.contains("--source\", \"opencode")
    }

    private static func jsonString(_ value: String) -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.withoutEscapingSlashes]
        let data = try! encoder.encode(value)
        return String(decoding: data, as: UTF8.self)
    }

    private static func hasGeneratedHeader(_ marker: String, in contents: String) -> Bool {
        contents.split(separator: "\n", maxSplits: 1, omittingEmptySubsequences: false).first
            == Substring("// \(marker). Do not edit.")
    }

}
