import Foundation
import Testing
@testable import NotchBotIntegrationCore

@Test func generatedOwnershipMarkersRecognizeCurrentAndPreviousManagedVersions() {
    let plugin = OpenCodePlugin.generate(hookPath: "/tmp/hook")
    #expect(OpenCodePlugin.isOwned(plugin))
    #expect(!OpenCodePlugin.isLegacyV01(plugin))
    let legacy = """
    // Generated by NotchBot. Remove this file to disable the integration.
    const args = ["/tmp/hook", "--source", "opencode"]
    Bun.spawn(args)
    process.unref()
    export const NotchBot = async () => ({})
    """
    #expect(OpenCodePlugin.isLegacyV01(legacy))
    #expect(!OpenCodePlugin.isLegacyV01("// Generated by NotchBot. Remove this file to disable the integration."))
    #expect(NotchBotIntegrationFiles.helperOwnershipMarker.contains("v0.3.2-r15"))
    let previous = """
    // Generated by NotchBot integration v0.2. Do not edit.
    function send(kind, sessionID) { Bun.spawn(args) }
    switch (event.type) { case "session.status": break }
    "tool.execute.before"
    """
    #expect(OpenCodePlugin.isPreviousVersion(previous))
    #expect(!OpenCodePlugin.isPreviousVersion("// Generated by NotchBot integration v0.2. Do not edit."))
    #expect(!OpenCodePlugin.isOwned("// Generated by NotchBot integration v0.2. Do not edit."))
    #expect(!OpenCodePlugin.isPreviousVersion(plugin))

    let previousV021 = previous.replacingOccurrences(of: "v0.2.", with: "v0.2.1.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV021))
    let previousV022 = previous.replacingOccurrences(of: "v0.2.", with: "v0.2.2.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV022))
    let previousV023 = previous.replacingOccurrences(of: "v0.2.", with: "v0.2.3.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV023))
    let previousV023R11 = previous.replacingOccurrences(of: "v0.2.", with: "v0.2.3-r11.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV023R11))
    let previousV024R11 = previous.replacingOccurrences(of: "v0.2.", with: "v0.2.4-r11.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV024R11))
    let previousV024R12 = previous.replacingOccurrences(of: "v0.2.", with: "v0.2.4-r12.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV024R12))
    let previousV025R12 = previous.replacingOccurrences(of: "v0.2.", with: "v0.2.5-r12.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV025R12))
    let previousV030R13 = previous.replacingOccurrences(of: "v0.2.", with: "v0.3.0-r13.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV030R13))
    let previousV031R14 = previous.replacingOccurrences(of: "v0.2.", with: "v0.3.1-r14.")
    #expect(OpenCodePlugin.isPreviousVersion(previousV031R14))
    #expect(IntegrationInstallStatus.currentVersion == 15)
    #expect(IntegrationInstallStatus().version == IntegrationInstallStatus.currentVersion)
}
