import Foundation
import Testing
@testable import NotchBotIntegrationCore

@Test func privacyPolicyDefaultsToDisabledWhenMissingOrInvalid() throws {
    let missing = URL(fileURLWithPath: "/tmp/notchbot-policy-\(UUID().uuidString)")
    #expect(!IntegrationPrivacyPolicy.load(from: missing).assistantExcerptsEnabled)

    let directory = FileManager.default.temporaryDirectory
        .appendingPathComponent("notchbot-policy-tests-\(UUID().uuidString)")
    try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    defer { try? FileManager.default.removeItem(at: directory) }
    let invalid = directory.appendingPathComponent("policy.json")
    try Data("{\"assistantExcerptsEnabled\":true}".utf8).write(to: invalid)
    #expect(!IntegrationPrivacyPolicy.load(from: invalid).assistantExcerptsEnabled)
}

@Test func generatedOwnershipMarkersAreSpecificToV02() {
    let plugin = OpenCodePlugin.generate(hookPath: "/tmp/hook", assistantExcerptsEnabled: false)
    #expect(OpenCodePlugin.isOwned(plugin))
    #expect(!OpenCodePlugin.isLegacyV01(plugin))
    let legacy = """
    // Generated by NotchBot. Remove this file to disable the integration.
    const latestResponses = new Map()
    const args = ["/tmp/hook", "--source", "opencode"]
    Bun.spawn(args)
    """
    #expect(OpenCodePlugin.isLegacyV01(legacy))
    #expect(!OpenCodePlugin.isLegacyV01("// Generated by NotchBot. Remove this file to disable the integration."))
    #expect(NotchBotIntegrationFiles.helperOwnershipMarker.contains("v0.2"))
}
