import Foundation
import NotchBotCore
import ServiceManagement

@MainActor
final class IntegrationInstaller: ObservableObject {
    @Published private(set) var message = "Integrations not installed"
    @Published private(set) var launchesAtLogin = SMAppService.mainApp.status == .enabled

    private let fileManager = FileManager.default

    init() {
        let helperInstalled = fileManager.isExecutableFile(atPath: NotchBotPaths.installedHookURL.path)
        let openCodeInstalled = fileManager.fileExists(atPath: openCodePluginURL.path)
        let claudeInstalled = (try? String(contentsOf: claudeSettingsURL, encoding: .utf8))?
            .contains(NotchBotPaths.installedHookURL.path) == true

        if helperInstalled && openCodeInstalled && claudeInstalled {
            message = "OpenCode and Claude Code connected"
        } else if helperInstalled || openCodeInstalled || claudeInstalled {
            message = "Integration setup incomplete"
        }
    }

    func install() {
        do {
            let hookURL = try installHookExecutable()
            try installOpenCodePlugin(hookURL: hookURL)
            try installClaudeHooks(hookURL: hookURL)
            message = "OpenCode and Claude Code connected"
        } catch {
            message = "Installation failed: \(error.localizedDescription)"
        }
    }

    func uninstall() {
        do {
            let pluginURL = openCodePluginURL
            if fileManager.fileExists(atPath: pluginURL.path) {
                try fileManager.removeItem(at: pluginURL)
            }
            try removeClaudeHooks()
            if fileManager.fileExists(atPath: NotchBotPaths.installedHookURL.path) {
                try fileManager.removeItem(at: NotchBotPaths.installedHookURL)
            }
            message = "Integrations removed"
        } catch {
            message = "Removal failed: \(error.localizedDescription)"
        }
    }

    func toggleLaunchAtLogin() {
        do {
            if SMAppService.mainApp.status == .enabled {
                try SMAppService.mainApp.unregister()
            } else {
                try SMAppService.mainApp.register()
            }
            launchesAtLogin = SMAppService.mainApp.status == .enabled
        } catch {
            message = "Launch at login failed: \(error.localizedDescription)"
        }
    }

    private func installHookExecutable() throws -> URL {
        let destination = NotchBotPaths.installedHookURL
        try fileManager.createDirectory(at: destination.deletingLastPathComponent(), withIntermediateDirectories: true)
        if fileManager.fileExists(atPath: destination.path) {
            try fileManager.removeItem(at: destination)
        }

        guard let source = bundledHookExecutable else {
            throw CocoaError(.fileNoSuchFile, userInfo: [NSFilePathErrorKey: "notchbot-hook"])
        }
        try fileManager.copyItem(at: source, to: destination)
        try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: destination.path)
        return destination
    }

    private var bundledHookExecutable: URL? {
        if let helper = Bundle.main.url(forAuxiliaryExecutable: "notchbot-hook") {
            return helper
        }
        let packagedHelper = Bundle.main.bundleURL
            .appendingPathComponent("Contents/Helpers", isDirectory: true)
            .appendingPathComponent("notchbot-hook")
        if fileManager.isExecutableFile(atPath: packagedHelper.path) {
            return packagedHelper
        }
        guard let executable = Bundle.main.executableURL else { return nil }
        let developmentHelper = executable.deletingLastPathComponent().appendingPathComponent("notchbot-hook")
        return fileManager.isExecutableFile(atPath: developmentHelper.path) ? developmentHelper : nil
    }

    private var openCodePluginURL: URL {
        fileManager.homeDirectoryForCurrentUser
            .appendingPathComponent(".config/opencode/plugins", isDirectory: true)
            .appendingPathComponent("notchbot.js")
    }

    private func installOpenCodePlugin(hookURL: URL) throws {
        let pluginURL = openCodePluginURL
        try fileManager.createDirectory(at: pluginURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        let escapedHookPath = hookURL.path
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")

        let plugin = """
        // Generated by NotchBot. Remove this file to disable the integration.
        const hookPath = "\(escapedHookPath)"

        const messageSessions = new Map()
        const latestResponses = new Map()

        function excerpt(value) {
          if (!value) return null
          const normalized = value.replace(/\\s+/g, " ").trim()
          return normalized.length > 240 ? normalized.slice(0, 237).trimEnd() + "..." : normalized
        }

        function send(kind, sessionID, reason, directory, expiresAfter, summary) {
          const args = [hookPath, "--source", "opencode", "--kind", kind, "--session", sessionID]
          if (reason) args.push("--reason", reason)
          if (directory) args.push("--cwd", directory)
          if (expiresAfter) args.push("--expires-after", String(expiresAfter))
          if (summary) args.push("--summary", excerpt(summary))
          const process = Bun.spawn(args, { stdin: "ignore", stdout: "ignore", stderr: "ignore" })
          process.unref()
        }

        export const NotchBot = async ({ directory }) => ({
          event: async ({ event }) => {
            const properties = event.properties ?? {}
            const sessionID = properties.sessionID ?? properties.info?.id

            if (event.type === "message.updated" && properties.info?.role === "assistant") {
              messageSessions.set(properties.info.id, properties.info.sessionID)
            }
            if (event.type === "message.part.updated" && properties.part?.type === "text") {
              const partSessionID = messageSessions.get(properties.part.messageID)
              if (partSessionID) latestResponses.set(partSessionID, properties.part.text)
            }
            if (!sessionID) return

            switch (event.type) {
              case "session.status":
                if (properties.status?.type === "busy" || properties.status?.type === "retry") {
                  send("working", sessionID, null, directory, null, null)
                } else if (properties.status?.type === "idle") {
                  send("attention", sessionID, "OpenCode finished working", directory, 2.5, latestResponses.get(sessionID))
                }
                break
              case "session.idle":
                send("attention", sessionID, "OpenCode finished working", directory, 2.5, latestResponses.get(sessionID))
                break
              case "permission.asked":
              case "permission.v2.asked":
                send("attention", sessionID, "OpenCode needs permission", directory, null, null)
                break
              case "question.asked":
              case "question.v2.asked":
                send("attention", sessionID, "OpenCode has a question", directory, null, null)
                break
              case "permission.replied":
              case "permission.v2.replied":
              case "question.replied":
              case "question.v2.replied":
                send("working", sessionID, null, directory, null, null)
                break
              case "session.error":
                send("attention", sessionID, "OpenCode encountered an error", directory, null, null)
                break
              case "session.deleted":
                send("cleared", sessionID, null, directory, null, null)
                latestResponses.delete(sessionID)
                break
            }
          },
          "tool.execute.before": async (input) => {
            send("working", input.sessionID, null, directory, null, null)
          },
        })
        """
        try Data(plugin.utf8).write(to: pluginURL, options: .atomic)
    }

    private var claudeSettingsURL: URL {
        fileManager.homeDirectoryForCurrentUser.appendingPathComponent(".claude/settings.json")
    }

    private func installClaudeHooks(hookURL: URL) throws {
        let settingsURL = claudeSettingsURL
        try fileManager.createDirectory(at: settingsURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        var settings = try readJSONObject(at: settingsURL)
        var hooks = settings["hooks"] as? [String: Any] ?? [:]

        hooks = removingNotchBotHooks(from: hooks)
        appendClaudeHook(event: "UserPromptSubmit", kind: "working", reason: nil, matcher: nil, expiresAfter: nil, hookURL: hookURL, hooks: &hooks)
        appendClaudeHook(event: "PreToolUse", kind: "working", reason: nil, matcher: nil, expiresAfter: nil, hookURL: hookURL, hooks: &hooks)
        appendClaudeHook(event: "PermissionRequest", kind: "attention", reason: "Claude Code needs permission", matcher: nil, expiresAfter: nil, hookURL: hookURL, hooks: &hooks)
        appendClaudeHook(event: "Notification", kind: "attention", reason: "Claude Code needs permission", matcher: "permission_prompt|agent_needs_input", expiresAfter: nil, hookURL: hookURL, hooks: &hooks)
        appendClaudeHook(event: "Notification", kind: "attention", reason: "Claude Code finished working", matcher: "idle_prompt", expiresAfter: 2.5, hookURL: hookURL, hooks: &hooks)
        appendClaudeHook(event: "Stop", kind: "attention", reason: "Claude Code finished working", matcher: nil, expiresAfter: 2.5, hookURL: hookURL, hooks: &hooks)
        appendClaudeHook(event: "SessionEnd", kind: "cleared", reason: nil, matcher: nil, expiresAfter: nil, hookURL: hookURL, hooks: &hooks)
        settings["hooks"] = hooks

        if fileManager.fileExists(atPath: settingsURL.path) {
            let backupURL = settingsURL.appendingPathExtension("notchbot-backup")
            try? fileManager.removeItem(at: backupURL)
            try fileManager.copyItem(at: settingsURL, to: backupURL)
        }
        let data = try JSONSerialization.data(withJSONObject: settings, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
        try data.write(to: settingsURL, options: .atomic)
    }

    private func appendClaudeHook(
        event: String,
        kind: String,
        reason: String?,
        matcher: String?,
        expiresAfter: TimeInterval?,
        hookURL: URL,
        hooks: inout [String: Any]
    ) {
        var args = ["--source", "claude", "--kind", kind]
        if let reason {
            args += ["--reason", reason]
        }
        if let expiresAfter {
            args += ["--expires-after", String(expiresAfter)]
        }
        let handler: [String: Any] = [
            "type": "command",
            "command": hookURL.path,
            "args": args,
            "timeout": 5,
        ]
        var group: [String: Any] = ["hooks": [handler]]
        if let matcher {
            group["matcher"] = matcher
        }
        var groups = hooks[event] as? [[String: Any]] ?? []
        groups.append(group)
        hooks[event] = groups
    }

    private func removeClaudeHooks() throws {
        let settingsURL = claudeSettingsURL
        guard fileManager.fileExists(atPath: settingsURL.path) else { return }
        var settings = try readJSONObject(at: settingsURL)
        let hooks = settings["hooks"] as? [String: Any] ?? [:]
        settings["hooks"] = removingNotchBotHooks(from: hooks)
        let data = try JSONSerialization.data(withJSONObject: settings, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
        try data.write(to: settingsURL, options: .atomic)
    }

    private func removingNotchBotHooks(from hooks: [String: Any]) -> [String: Any] {
        var result: [String: Any] = [:]
        for (event, value) in hooks {
            guard let groups = value as? [[String: Any]] else {
                result[event] = value
                continue
            }
            let remainingGroups = groups.compactMap { group -> [String: Any]? in
                guard let handlers = group["hooks"] as? [[String: Any]] else { return group }
                let remainingHandlers = handlers.filter { handler in
                    guard let command = handler["command"] as? String else { return true }
                    return command != NotchBotPaths.installedHookURL.path
                }
                guard !remainingHandlers.isEmpty else { return nil }
                var updated = group
                updated["hooks"] = remainingHandlers
                return updated
            }
            if !remainingGroups.isEmpty {
                result[event] = remainingGroups
            }
        }
        return result
    }

    private func readJSONObject(at url: URL) throws -> [String: Any] {
        guard fileManager.fileExists(atPath: url.path) else { return [:] }
        let data = try Data(contentsOf: url)
        guard !data.isEmpty else { return [:] }
        guard let object = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw CocoaError(.propertyListReadCorrupt)
        }
        return object
    }
}
